-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Ball_Ind_Dost"
(
    "Ball" bigint NOT NULL,
    "PK_Facultet" integer NOT NULL,
    CONSTRAINT "PK_Ball_Ind_Dost" PRIMARY KEY ("PK_Facultet")
);

CREATE TABLE IF NOT EXISTS public."Dokument"
(
    "Seriya" character varying(32) COLLATE pg_catalog."default",
    "Nomer" character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "Kem_vydan" character varying(128) COLLATE pg_catalog."default",
    "Kod_podrazd" numeric(6, 0),
    "Data_vydachi" date NOT NULL,
    "Strana" character varying(64) COLLATE pg_catalog."default",
    "FIO_v_dokumente" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "Data_rozhdeniya" date,
    "Pol" character varying(8) COLLATE pg_catalog."default",
    "Mesto_rozhdeniya" character varying(128) COLLATE pg_catalog."default",
    "PK_Vid_dokumenta" integer,
    "PK_Dokument" serial NOT NULL,
    "PK_Fizicheskoe_litso" integer NOT NULL,
    CONSTRAINT "PK_Dokument" PRIMARY KEY ("PK_Dokument", "PK_Fizicheskoe_litso")
);

CREATE TABLE IF NOT EXISTS public."Fakultet"
(
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "Abreviatura" character(8) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "Telefon" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "FIO_decan" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "PK_Facultet" serial NOT NULL,
    CONSTRAINT "PK_Fakultet" PRIMARY KEY ("PK_Facultet")
);

CREATE TABLE IF NOT EXISTS public."Fizicheskoe_litso"
(
    "Imya" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Familiya" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Otchestvo" character varying(32) COLLATE pg_catalog."default",
    "Data_rozhdeniya" date NOT NULL,
    "Telefon" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "PK_Fizicheskoe_litso" serial NOT NULL,
    CONSTRAINT "PK_Fizicheskoe_litso" PRIMARY KEY ("PK_Fizicheskoe_litso")
);

CREATE TABLE IF NOT EXISTS public."Forma_obucheniya"
(
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "PK_Forma_obucheniya" serial NOT NULL,
    CONSTRAINT "PK_Forma_obucheniya" PRIMARY KEY ("PK_Forma_obucheniya")
);

CREATE TABLE IF NOT EXISTS public."KCP"
(
    "Summa" numeric(3, 0) NOT NULL,
    "PK_Facultet" integer,
    "PK_Forma_obucheniya" integer,
    "PK_KCP" serial NOT NULL,
    "PK_Spetsialnost" integer,
    CONSTRAINT "PK_KCP" PRIMARY KEY ("PK_KCP")
);

CREATE TABLE IF NOT EXISTS public."Kategoriya_obucheniya"
(
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "PK_Kategoriya_obucheniya" serial NOT NULL,
    CONSTRAINT "PK_Kategoriya_obucheniya" PRIMARY KEY ("PK_Kategoriya_obucheniya")
);

CREATE TABLE IF NOT EXISTS public."Konkursnaya_gruppa"
(
    "Kolichestvo_mest" numeric(6, 0) NOT NULL,
    "PK_Konkursnaya_gruppa" serial NOT NULL,
    "PK_KCP" integer,
    "PK_Kategoriya_obucheniya" integer,
    "Daty_podachi" daterange NOT NULL,
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Konkursnaya_gruppa" PRIMARY KEY ("PK_Konkursnaya_gruppa")
);

CREATE TABLE IF NOT EXISTS public."Lichnoe_delo"
(
    "PK_Lichnoe_delo" serial NOT NULL,
    "PK_Fizicheskoe_litso" integer,
    "Nomer" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Original" boolean NOT NULL,
    CONSTRAINT "PK_Lichnoe_delo" PRIMARY KEY ("PK_Lichnoe_delo")
);

CREATE TABLE IF NOT EXISTS public."Predmet"
(
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "PK_Predmet" serial NOT NULL,
    CONSTRAINT "PK_Predmet" PRIMARY KEY ("PK_Predmet")
);

CREATE TABLE IF NOT EXISTS public."Predmet_spetsialnost"
(
    "Prioritet" numeric(1, 0) NOT NULL,
    "PK_Spetsialnost" integer NOT NULL,
    "PK_Predmet" integer NOT NULL,
    "PK_Predmet_spetsianost" serial NOT NULL,
    CONSTRAINT "PK_Predmet_spetsialnost" PRIMARY KEY ("PK_Predmet_spetsianost", "PK_Spetsialnost", "PK_Predmet")
);

CREATE TABLE IF NOT EXISTS public."Prikaz"
(
    "Nomer" character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "Data" date NOT NULL,
    "Chei" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "Utverzhdeno" boolean NOT NULL,
    "PK_Forma_obucheniya" integer,
    "PK_Kategoriya_obucheniya" integer,
    "PK_Prikaz" serial NOT NULL,
    CONSTRAINT "PK_Prikaz" PRIMARY KEY ("PK_Prikaz")
);

CREATE TABLE IF NOT EXISTS public."Rezultat"
(
    "Ball" numeric(3, 0) NOT NULL,
    "PK_Predmet" integer,
    "PK_Tip_otsenki" integer,
    "PK_Zayavlenie" integer NOT NULL,
    "PK_Rezultat" serial NOT NULL,
    "PK_Lichnoe_delo" integer NOT NULL,
    CONSTRAINT "PK_Rezultat" PRIMARY KEY ("PK_Rezultat", "PK_Zayavlenie", "PK_Lichnoe_delo")
);

CREATE TABLE IF NOT EXISTS public."Rezultat_history"
(
    "PK_Rezultat_history" serial NOT NULL,
    "PK_Rezultat" integer NOT NULL,
    "Ball" numeric(3, 0) NOT NULL,
    "Modified_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Change_type" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Rezultat_history_pkey" PRIMARY KEY ("PK_Rezultat_history")
);

CREATE TABLE IF NOT EXISTS public."Spetsialnost"
(
    "Kod" numeric(7, 0) NOT NULL,
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "PK_Spetsialnost" serial NOT NULL,
    CONSTRAINT "PK_Spetsialnost" PRIMARY KEY ("PK_Spetsialnost")
);

CREATE TABLE IF NOT EXISTS public."Stroka_prikaza"
(
    "PK_Prikaz" integer NOT NULL,
    "PK_Stroka_prikaza" serial NOT NULL,
    "PK_Zayavlenie" integer NOT NULL,
    "PK_Lichnoe_delo" integer NOT NULL,
    CONSTRAINT "PK_Stroka_prikaza" PRIMARY KEY ("PK_Stroka_prikaza", "PK_Zayavlenie", "PK_Prikaz", "PK_Lichnoe_delo")
);

CREATE TABLE IF NOT EXISTS public."Tip_otsenki"
(
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "PK_Tip_otsenki" serial NOT NULL,
    CONSTRAINT "PK_Tip_otsenki" PRIMARY KEY ("PK_Tip_otsenki")
);

CREATE TABLE IF NOT EXISTS public."Vid_dokumenta"
(
    "Naim" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "PK_Vid_dokumenta" serial NOT NULL,
    CONSTRAINT "PK_Vid_dokumenta" PRIMARY KEY ("PK_Vid_dokumenta")
);

CREATE TABLE IF NOT EXISTS public."Zayavlenie"
(
    "Summa_ballov" numeric(3, 0),
    "Prioritet" numeric(3, 0) NOT NULL,
    "PK_Konkursnaya_gruppa" integer,
    "PK_Zayavlenie" serial NOT NULL,
    "PK_Lichnoe_delo" integer NOT NULL,
    "Data_podachi" date NOT NULL,
    "Napravlenie" integer NOT NULL,
    CONSTRAINT "PK_Zayavlenie" PRIMARY KEY ("PK_Zayavlenie", "PK_Lichnoe_delo")
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.django_site
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    domain character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_site_pkey PRIMARY KEY (id),
    CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain)
);

ALTER TABLE IF EXISTS public."Ball_Ind_Dost"
    ADD CONSTRAINT "Relationship38" FOREIGN KEY ("PK_Facultet")
    REFERENCES public."Fakultet" ("PK_Facultet") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "PK_Ball_Ind_Dost"
    ON public."Ball_Ind_Dost"("PK_Facultet");


ALTER TABLE IF EXISTS public."Dokument"
    ADD CONSTRAINT "Relationship39" FOREIGN KEY ("PK_Vid_dokumenta")
    REFERENCES public."Vid_dokumenta" ("PK_Vid_dokumenta") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Relationship39"
    ON public."Dokument"("PK_Vid_dokumenta");


ALTER TABLE IF EXISTS public."Dokument"
    ADD CONSTRAINT "Relationship48" FOREIGN KEY ("PK_Fizicheskoe_litso")
    REFERENCES public."Fizicheskoe_litso" ("PK_Fizicheskoe_litso") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."KCP"
    ADD CONSTRAINT "Relationship21" FOREIGN KEY ("PK_Facultet")
    REFERENCES public."Fakultet" ("PK_Facultet") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship21"
    ON public."KCP"("PK_Facultet");


ALTER TABLE IF EXISTS public."KCP"
    ADD CONSTRAINT "Relationship22" FOREIGN KEY ("PK_Spetsialnost")
    REFERENCES public."Spetsialnost" ("PK_Spetsialnost") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship22"
    ON public."KCP"("PK_Spetsialnost");


ALTER TABLE IF EXISTS public."KCP"
    ADD CONSTRAINT "Relationship23" FOREIGN KEY ("PK_Forma_obucheniya")
    REFERENCES public."Forma_obucheniya" ("PK_Forma_obucheniya") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship23"
    ON public."KCP"("PK_Forma_obucheniya");


ALTER TABLE IF EXISTS public."Konkursnaya_gruppa"
    ADD CONSTRAINT "Relationship24" FOREIGN KEY ("PK_KCP")
    REFERENCES public."KCP" ("PK_KCP") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship24"
    ON public."Konkursnaya_gruppa"("PK_KCP");


ALTER TABLE IF EXISTS public."Konkursnaya_gruppa"
    ADD CONSTRAINT "Relationship25" FOREIGN KEY ("PK_Kategoriya_obucheniya")
    REFERENCES public."Kategoriya_obucheniya" ("PK_Kategoriya_obucheniya") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship25"
    ON public."Konkursnaya_gruppa"("PK_Kategoriya_obucheniya");


ALTER TABLE IF EXISTS public."Lichnoe_delo"
    ADD CONSTRAINT "Relationship28" FOREIGN KEY ("PK_Fizicheskoe_litso")
    REFERENCES public."Fizicheskoe_litso" ("PK_Fizicheskoe_litso") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship28"
    ON public."Lichnoe_delo"("PK_Fizicheskoe_litso");


ALTER TABLE IF EXISTS public."Predmet_spetsialnost"
    ADD CONSTRAINT "Relationship44" FOREIGN KEY ("PK_Spetsialnost")
    REFERENCES public."Spetsialnost" ("PK_Spetsialnost") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Predmet_spetsialnost"
    ADD CONSTRAINT "Relationship45" FOREIGN KEY ("PK_Predmet")
    REFERENCES public."Predmet" ("PK_Predmet") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Prikaz"
    ADD CONSTRAINT "Relationship42" FOREIGN KEY ("PK_Kategoriya_obucheniya")
    REFERENCES public."Kategoriya_obucheniya" ("PK_Kategoriya_obucheniya") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship42"
    ON public."Prikaz"("PK_Kategoriya_obucheniya");


ALTER TABLE IF EXISTS public."Prikaz"
    ADD CONSTRAINT "Relationship43" FOREIGN KEY ("PK_Forma_obucheniya")
    REFERENCES public."Forma_obucheniya" ("PK_Forma_obucheniya") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship43"
    ON public."Prikaz"("PK_Forma_obucheniya");


ALTER TABLE IF EXISTS public."Rezultat"
    ADD CONSTRAINT "Relationship30" FOREIGN KEY ("PK_Zayavlenie", "PK_Lichnoe_delo")
    REFERENCES public."Zayavlenie" ("PK_Zayavlenie", "PK_Lichnoe_delo") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Rezultat"
    ADD CONSTRAINT "Relationship31" FOREIGN KEY ("PK_Predmet")
    REFERENCES public."Predmet" ("PK_Predmet") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship31"
    ON public."Rezultat"("PK_Predmet");


ALTER TABLE IF EXISTS public."Rezultat"
    ADD CONSTRAINT "Relationship46" FOREIGN KEY ("PK_Tip_otsenki")
    REFERENCES public."Tip_otsenki" ("PK_Tip_otsenki") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship46"
    ON public."Rezultat"("PK_Tip_otsenki");


ALTER TABLE IF EXISTS public."Stroka_prikaza"
    ADD CONSTRAINT "Relationship34" FOREIGN KEY ("PK_Zayavlenie", "PK_Lichnoe_delo")
    REFERENCES public."Zayavlenie" ("PK_Zayavlenie", "PK_Lichnoe_delo") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Stroka_prikaza"
    ADD CONSTRAINT "Relationship41" FOREIGN KEY ("PK_Prikaz")
    REFERENCES public."Prikaz" ("PK_Prikaz") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Zayavlenie"
    ADD CONSTRAINT "Relationship26" FOREIGN KEY ("PK_Konkursnaya_gruppa")
    REFERENCES public."Konkursnaya_gruppa" ("PK_Konkursnaya_gruppa") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Relationship26"
    ON public."Zayavlenie"("PK_Konkursnaya_gruppa");


ALTER TABLE IF EXISTS public."Zayavlenie"
    ADD CONSTRAINT "Relationship27" FOREIGN KEY ("PK_Lichnoe_delo")
    REFERENCES public."Lichnoe_delo" ("PK_Lichnoe_delo") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);

END;