# Generated by Django 5.1.4 on 2024-12-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('naim', models.CharField(db_column='Naim', max_length=64)),
                ('abreviatura', models.CharField(db_column='Abreviatura', max_length=8)),
                ('email', models.CharField(db_column='Email', max_length=64)),
                ('telefon', models.CharField(db_column='Telefon', max_length=15)),
                ('fio_decan', models.CharField(db_column='FIO_decan', max_length=64)),
                ('pk_facultet', models.AutoField(db_column='PK_Facultet', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Fakultet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('seriya', models.CharField(blank=True, db_column='Seriya', max_length=32, null=True)),
                ('nomer', models.CharField(db_column='Nomer', max_length=16)),
                ('kem_vydan', models.CharField(blank=True, db_column='Kem_vydan', max_length=128, null=True)),
                ('kod_podrazd', models.DecimalField(blank=True, db_column='Kod_podrazd', decimal_places=0, max_digits=6, null=True)),
                ('data_vydachi', models.DateField(db_column='Data_vydachi')),
                ('strana', models.CharField(blank=True, db_column='Strana', max_length=64, null=True)),
                ('fio_v_dokumente', models.CharField(db_column='FIO_v_dokumente', max_length=64)),
                ('data_rozhdeniya', models.DateField(blank=True, db_column='Data_rozhdeniya', null=True)),
                ('pol', models.CharField(blank=True, db_column='Pol', max_length=8, null=True)),
                ('mesto_rozhdeniya', models.CharField(blank=True, db_column='Mesto_rozhdeniya', max_length=128, null=True)),
                ('pk_dokument', models.AutoField(db_column='PK_Dokument', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Dokument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FizicheskoeLitso',
            fields=[
                ('imya', models.CharField(db_column='Imya', max_length=32)),
                ('familiya', models.CharField(db_column='Familiya', max_length=32)),
                ('otchestvo', models.CharField(blank=True, db_column='Otchestvo', max_length=32, null=True)),
                ('data_rozhdeniya', models.DateField(db_column='Data_rozhdeniya')),
                ('telefon', models.CharField(db_column='Telefon', max_length=15)),
                ('pk_fizicheskoe_litso', models.AutoField(db_column='PK_Fizicheskoe_litso', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Fizicheskoe_litso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaObucheniya',
            fields=[
                ('naim', models.CharField(db_column='Naim', max_length=64)),
                ('pk_forma_obucheniya', models.AutoField(db_column='PK_Forma_obucheniya', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Forma_obucheniya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriyaObucheniya',
            fields=[
                ('naim', models.CharField(db_column='Naim', max_length=64)),
                ('pk_kategoriya_obucheniya', models.AutoField(db_column='PK_Kategoriya_obucheniya', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Kategoriya_obucheniya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kcp',
            fields=[
                ('summa', models.DecimalField(db_column='Summa', decimal_places=0, max_digits=3)),
                ('pk_kcp', models.AutoField(db_column='PK_KCP', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'KCP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KonkursnayaGruppa',
            fields=[
                ('kolichestvo_mest', models.DecimalField(db_column='Kolichestvo_mest', decimal_places=0, max_digits=6)),
                ('pk_konkursnaya_gruppa', models.AutoField(db_column='PK_Konkursnaya_gruppa', primary_key=True, serialize=False)),
                ('daty_podachi', models.TextField(db_column='Daty_podachi')),
                ('naim', models.CharField(db_column='Naim', max_length=64)),
            ],
            options={
                'db_table': 'Konkursnaya_gruppa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LichnoeDelo',
            fields=[
                ('pk_lichnoe_delo', models.AutoField(db_column='PK_Lichnoe_delo', primary_key=True, serialize=False)),
                ('nomer', models.CharField(db_column='Nomer', max_length=32)),
                ('original', models.BooleanField(db_column='Original')),
            ],
            options={
                'db_table': 'Lichnoe_delo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('naim', models.CharField(db_column='Naim', max_length=64)),
                ('pk_predmet', models.AutoField(db_column='PK_Predmet', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Predmet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredmetSpetsialnost',
            fields=[
                ('prioritet', models.DecimalField(db_column='Prioritet', decimal_places=0, max_digits=1)),
                ('pk_predmet_spetsianost', models.AutoField(db_column='PK_Predmet_spetsianost', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Predmet_spetsialnost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prikaz',
            fields=[
                ('nomer', models.CharField(db_column='Nomer', max_length=16)),
                ('data', models.DateField(db_column='Data')),
                ('chei', models.CharField(db_column='Chei', max_length=128)),
                ('utverzhdeno', models.BooleanField(db_column='Utverzhdeno')),
                ('pk_prikaz', models.AutoField(db_column='PK_Prikaz', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Prikaz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rezultat',
            fields=[
                ('ball', models.DecimalField(db_column='Ball', decimal_places=0, max_digits=3)),
                ('pk_rezultat', models.AutoField(db_column='PK_Rezultat', primary_key=True, serialize=False)),
                ('pk_lichnoe_delo', models.IntegerField(db_column='PK_Lichnoe_delo')),
            ],
            options={
                'db_table': 'Rezultat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RezultatHistory',
            fields=[
                ('pk_rezultat_history', models.AutoField(db_column='PK_Rezultat_history', primary_key=True, serialize=False)),
                ('pk_rezultat', models.IntegerField(db_column='PK_Rezultat')),
                ('ball', models.DecimalField(db_column='Ball', decimal_places=0, max_digits=3)),
                ('modified_at', models.DateTimeField(db_column='Modified_at')),
                ('change_type', models.CharField(db_column='Change_type', max_length=10)),
            ],
            options={
                'db_table': 'Rezultat_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spetsialnost',
            fields=[
                ('kod', models.DecimalField(db_column='Kod', decimal_places=0, max_digits=7)),
                ('naim', models.CharField(db_column='Naim', max_length=64)),
                ('pk_spetsialnost', models.AutoField(db_column='PK_Spetsialnost', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Spetsialnost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StrokaPrikaza',
            fields=[
                ('pk_stroka_prikaza', models.AutoField(db_column='PK_Stroka_prikaza', primary_key=True, serialize=False)),
                ('pk_lichnoe_delo', models.IntegerField(db_column='PK_Lichnoe_delo')),
            ],
            options={
                'db_table': 'Stroka_prikaza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipOtsenki',
            fields=[
                ('naim', models.CharField(db_column='Naim', max_length=64)),
                ('pk_tip_otsenki', models.AutoField(db_column='PK_Tip_otsenki', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tip_otsenki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidDokumenta',
            fields=[
                ('naim', models.CharField(db_column='Naim', max_length=64)),
                ('pk_vid_dokumenta', models.AutoField(db_column='PK_Vid_dokumenta', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Vid_dokumenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zayavlenie',
            fields=[
                ('napravlenie', models.CharField(db_column='Napravlenie', max_length=64)),
                ('summa_ballov', models.DecimalField(db_column='Summa_ballov', decimal_places=0, max_digits=3)),
                ('prioritet', models.DecimalField(db_column='Prioritet', decimal_places=0, max_digits=3)),
                ('pk_zayavlenie', models.AutoField(db_column='PK_Zayavlenie', primary_key=True, serialize=False)),
                ('data_podachi', models.DateField(db_column='Data_podachi')),
            ],
            options={
                'db_table': 'Zayavlenie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BallIndDost',
            fields=[
                ('ball', models.BigIntegerField(db_column='Ball')),
                ('pk_facultet', models.OneToOneField(db_column='PK_Facultet', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='kust_site.fakultet')),
            ],
            options={
                'db_table': 'Ball_Ind_Dost',
                'managed': False,
            },
        ),
    ]
